name: "CI"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  ci:
    name: "CI"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Check if library is build for production"
        run: "npm run build && git status --porcelain | wc -l | read CHANGED_FILES && [[ $CHANGED_FILES > 0 ]] && CHANGED_FILES=1;exit $CHANGED_FILES"

      - name: "Run linter"
        run: "npm run lint"

      - name: "Run tests"
        run: "npm run test"